image: ghcr.io/scrtlabs/localsecret-gitpod:v1.9.0-beta.1

tasks:
  - name: Faucet
    command: |
      node /home/gitpod/faucet_server.js
  - name: LocalSecret
    command: |
      cd /home/gitpod/ && SCRT_SGX_STORAGE=/opt/secret/.sgx_secrets /home/gitpod/bootstrap_init.sh false
  - name: Terminal
    command: |
      echo "Hello and welcome to the Secret Network"

jetbrains:
  intellij:
    plugins:
      - io.digiline.secretideplugin
      - org.rust.lang
      - org.toml.lang

ports:
  - port: 26657
    onOpen: ignore
    visibility: public
  - port: 9091
    onOpen: ignore
    visibility: public
  - port: 9090
    onOpen: ignore
    visibility: public
  - port: 5000
    onOpen: ignore
    visibility: public
  - port: 1317
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
  - port: 24000
    onOpen: ignore
