/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eNE44pcQYdL
 */
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Button, buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export function DropContent() {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base font-medium">
          Upload your files
        </CardTitle>
        <CardDescription className="text-sm font-normal">
          Drag and drop or select files
        </CardDescription>
      </CardHeader>
      <CardContent className="flex justify-center items-center p-6">
        <div className="w-full border-dashed border-2  border-gray-300 rounded-lg p-4 text-center">
          <div className="text-sm text-gray-500">Drag and drop your files</div>
        </div>
      </CardContent>
      <CardFooter>
        <div className="flex w-full gap-2">
          <input type="file" className="hidden" id="file" name="file" />
          <label
            className={cn(buttonVariants({ variant: "outline" }), "flex-1")}
            htmlFor="file"
          >
            Select files
          </label>
          <Button className="flex-1" variant="ghost">
            Remove all
          </Button>
        </div>
      </CardFooter>
    </Card>
  );
}

function UploadIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 1-2 2H5a2 1-2-2v-4" />
      <polyline points="17 8 12 3 7" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}

function TrashIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2v2" />
    </svg>
  );
}
